// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3lMhSUXO3F5S2Sf3SbyMFQRwfGUHix80',
    appId: '1:665630150437:web:9e56534892371e29d414cc',
    messagingSenderId: '665630150437',
    projectId: 'altheimer-aba5d',
    authDomain: 'altheimer-aba5d.firebaseapp.com',
    storageBucket: 'altheimer-aba5d.appspot.com',
    measurementId: 'G-VGDMRDX129',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQftn-x9OfHkEGwxGukVM-bGdUiPEYvR8',
    appId: '1:665630150437:android:97f9e729cfc4f927d414cc',
    messagingSenderId: '665630150437',
    projectId: 'altheimer-aba5d',
    storageBucket: 'altheimer-aba5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKViE5gycFtYVZ-4DL9jAtOQIxg28-vGc',
    appId: '1:665630150437:ios:e63897b69bc0e8c6d414cc',
    messagingSenderId: '665630150437',
    projectId: 'altheimer-aba5d',
    storageBucket: 'altheimer-aba5d.appspot.com',
    iosBundleId: 'com.example.althhimerApp',
  );

}